version: 2
updates:
  - package-ecosystem: "npm"
    directory: "tests/typescript"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "tests/python"
    schedule:
      interval: "daily"
