name: Test Language Functions
on:
    pull_request:
        branches:
            - main
jobs:
    typescript:
        name: Typescript Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - name: yarn install
              run: yarn --cwd ./tests/typescript install
            - name: mocha tests
              run: yarn --cwd ./tests/typescript run test
    python:
        name: Python Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2 # Checking out the repo

            - name: CD into the py test dir
              run: cd ./tests/python/

            - name: Install dependecies
              uses: VaultVulp/action-pipenv@v2.0.1
              with:
                  command: install -d # Install all dependencies, including development ones

            - name: Test
              uses: VaultVulp/action-pipenv@v2.0.1
              with:
                  command: run test
